### PR TITLE
Placeholder for lack of Github Email/Username

### LINKED ISSUE #18: Raise a warning if user does not have a git user set
## Why
Gemspec authors config will be empty if the user has not set their `git config user.name` (or email) , hence making executables (like rubocop) to fail at runtime

## What
Raise a warning when the user does not have a git user name, and update the gemspec with a temporary author name, so that the tasks can continue to work properly

### PR DESCRIPTION
**Pull request by yez**
When git isn't configured with an email or username, add a placeholder
and issue a warning.

Also make a spec that asserts this functionality is working.

Closes #18

### CODE REVIEW

File: lib/rsgem/tasks/create_gem.rb [hunk 1]
```diff
@@ -32,6 +33,23 @@ def shell_command
           bundler_options
         ].compact.join(' ')
       end
+
+      def ensure_author
```
Comment (juanmanuelramallo) [inline lib/rsgem/tasks/create_gem.rb]: I'd rather extract this out to its own [task object](https://github.com/rootstrap/rsgem/tree/master/lib/rsgem/tasks), so that we practice the single responsibility principle. 

We can then call this new task from the main gem class https://github.com/rootstrap/rsgem/blob/master/lib/rsgem/gem.rb#L12 right before this line.

What do you think?

File: lib/rsgem/tasks/create_gem.rb [hunk 2]
```diff
@@ -32,6 +33,23 @@ def shell_command
...
+        temp_username = 'change_me'
+        temp_email = 'change_me@notanemail.com'
+        gemspec = File.read(context.gemspec_path)
+        unless system('git config user.email')
+          puts "Warning: No git email set, setting #{temp_email} for now, please change this before publishing your gem."
+          gemspec.gsub!(/(spec.email[^\[]+)\[([^\]]+)/, "\\1\['#{temp_email}'")
```
Comment (juanmanuelramallo) [inline lib/rsgem/tasks/create_gem.rb]: Do you think a simpler version of this regex would work, something like this maybe?

```suggestion
          gemspec.gsub!(/spec.email\s+=\s+.+/, "spec.email = '#{temp_email}'")
```

\s is used for the whitespaces. And we don't really care about maintaining the same amount of spaces in here (we are doing something similar here https://github.com/rootstrap/rsgem/blob/master/lib/rsgem/tasks/set_bundled_files.rb)

File: spec/cli_spec.rb [hunk 3]
```diff
@@ -55,6 +55,28 @@
         expect(File.exist?("#{gem_name}/.github/workflows/ci.yml")).to eq true
       end
     end
+
+    context 'without github config properly set' do
```
Comment (juanmanuelramallo) [inline spec/cli_spec.rb]:
```suggestion
    context 'without git config properly set' do
```

File: lib/rsgem/tasks/create_gem.rb [hunk 4]
```diff
@@ -32,6 +33,23 @@ def shell_command
           bundler_options
         ].compact.join(' ')
       end
+
+      def ensure_author
+        temp_username = 'change_me'
+        temp_email = 'change_me@notanemail.com'
+        gemspec = File.read(context.gemspec_path)
+        unless system('git config user.email')
```
Comment (juanmanuelramallo) [inline lib/rsgem/tasks/create_gem.rb]: I think this will always be evalueated as truthy, won't it?

**Review by juanmanuelramallo — COMMENTED** [review]
Hey @yez, thanks for the PR. Would you mind checking the CI (seems like rubocop analysis failed) and the comments I left?

File: lib/rsgem/tasks/create_gem.rb (hunk 1 above)
Comment (yez) [reply lib/rsgem/tasks/create_gem.rb]: I thought about doing this but didn't know if we'd ever want this task to run outside of creation. I am happy to extract it out.

File: lib/rsgem/tasks/create_gem.rb (hunk 4 above)
Comment (yez) [reply lib/rsgem/tasks/create_gem.rb]: I tested this with pry and then with the unit test to make sure it only overwrote the values if necessary. I can triple check though to make sure the return value of `system('git config user.email')` when its blank is `false`.

File: lib/rsgem/tasks/create_gem.rb (hunk 2 above)
Comment (yez) [reply lib/rsgem/tasks/create_gem.rb]: Does this preserve the `[]` around `authors` and `email` that the gemspec defaults with?

File: lib/rsgem/tasks/create_gem.rb (hunk 1 above)
Comment (juanmanuelramallo) [reply lib/rsgem/tasks/create_gem.rb]: Yeah that's right, I guess we wouldn't ever want to run this task outside of creation, but for the sake of keeping a tidy/organized codebase I think moving it out to its own task object wouldn't hurt.

File: lib/rsgem/tasks/create_gem.rb (hunk 2 above)
Comment (juanmanuelramallo) [reply lib/rsgem/tasks/create_gem.rb]: Oh you are right, I missed the brackets

```suggestion
          gemspec.gsub!(/spec.email\s+=\s+.+/, "spec.email = ['#{temp_email}']")
```

File: lib/rsgem/tasks/create_gem.rb (hunk 4 above)
Comment (juanmanuelramallo) [reply lib/rsgem/tasks/create_gem.rb]: I did test the same thing, with IRB instead of pry and I always got `true` surprisingly.

Comment (juanmanuelramallo) [reply lib/rsgem/tasks/create_gem.rb]: https://rubyapi.org/2.7/o/kernel#method-i-system so according to this

>system returns true if the command gives zero exit status, false for non zero exit status. Returns nil if command execution fails. An error status is available in $?.

Comment (yez) [reply lib/rsgem/tasks/create_gem.rb]: Ok I must have a bug in the test then and its always truthy. I'll remedy this.

Comment (yez) [reply lib/rsgem/tasks/create_gem.rb]: Since the tests use backticks and analyze the output, I did some manual testing in my CLI and here are the results:

1. Unset my git email 
2. Run `rsgem new foo` and inspect results => value is `false`
3. Set my git email
4. Run `rsgem new foo` and inspect results => value is `true`

So it looks like this works as expected. I will still move it to a new task. 

```sh
20:11:02 | rsgem | (error-if-no-github-user) -> git config --unset user.email

37: def ensure_author
    38:   temp_username = 'change_me'
    39:   temp_email = 'change_me@notanemail.com'
    40:   gemspec = File.read(context.gemspec_path)
    41:   require 'pry'
 => 42:   binding.pry
    43:   unless system('git config user.email')
    44:     puts "Warning: No git email set, setting #{temp_email} for now, please change this before publishing your gem."
    45:     gemspec.gsub!(/(spec.email[^\[]+)\[([^\]]+)/, "\\1\['#{temp_email}'")
    46:   end
    47:
    48:   unless system('git config user.name')
    49:     puts "Warning: No git username set, setting #{temp_username} for now, please change this before publishing your gem."
    50:     gemspec.gsub!(/(spec.authors[^\[]+)\[([^\]]+)/, "\\1\['#{temp_username}'")
    51:   end
    52:
    53:   File.write(context.gemspec_path, gemspec)
    54: end

[1] pry(#<RSGem::Tasks::CreateGem>)> value = system('git config user.email')
=> false

----------

20:13:03 | rsgem | (error-if-no-github-user) -> git config user.email 'yesbeckjs@gmail.com'
    37: def ensure_author
    38:   temp_username = 'change_me'
    39:   temp_email = 'change_me@notanemail.com'
    40:   gemspec = File.read(context.gemspec_path)
    41:   require 'pry'
 => 42:   binding.pry
    43:   unless system('git config user.email')
    44:     puts "Warning: No git email set, setting #{temp_email} for now, please change this before publishing your gem."
    45:     gemspec.gsub!(/(spec.email[^\[]+)\[([^\]]+)/, "\\1\['#{temp_email}'")
    46:   end
    47:
    48:   unless system('git config user.name')
    49:     puts "Warning: No git username set, setting #{temp_username} for now, please change this before publishing your gem."
    50:     gemspec.gsub!(/(spec.authors[^\[]+)\[([^\]]+)/, "\\1\['#{temp_username}'")
    51:   end
    52:
    53:   File.write(context.gemspec_path, gemspec)
    54: end

[1] pry(#<RSGem::Tasks::CreateGem>)> value = system('git config user.email')
yesbeckjs@gmail.com
true
```

**Review by juanmanuelramallo — APPROVED** [review]
This is great! Do you mind adding an entry in the changelog file right below master? https://github.com/rootstrap/rsgem/blob/master/CHANGELOG.md

**Comment by yez** [comment]
I updated the CHANGELOG, if we merge this in, I can rebase the other PR to avoid conflicts as I update the CHANGELOG again

File: CHANGELOG.md [hunk 5]
```diff
@@ -1,5 +1,8 @@
 # master
 
+* Add placeholder `email` and `name` when no git config is set, issuing
+    a warning while doing so.
```
Comment (juanmanuelramallo) [inline CHANGELOG.md]:
```suggestion
* Add placeholder `email` and `name` when no git user is set, issuing a warning while doing so.
    
    *Jake Yesbeck*
```
